"ONE" : NULL
"TWO" : NULL
"THREE" : NULL
"FOUR" : NULL
"FIST" : NULL
"OK" : NULL
"YEAH" : NULL
"ROCK" : NULL
"SPIDERMAN" : NULL
"Slide left" : NULL
"Slide right" : NULL
"Scrolling up" : NULL
"Scrolling down" : NULL
