ONE: option2
TWO: option2
THREE: option2
FOUR: option3
FIST: option2
OK: option2
YEAH: option2
ROCK: option2
SPIDERMAN: option2
Slide_left: option2
Slide_right: option1
Scrolling_up: option3
Scrolling_down: option3
VOICE: option3
